### ISSUE TITLE
Set Up Sonarqube

### ISSUE THREAD

**Issue by digitalfishpond** [NephologyFJ/nephology#10]
[DoD]
TBD

**Comment by victorhrsilva** [comment]
Interesting article about it: https://docs.travis-ci.com/user/sonarqube/

**Comment by grubskim** [comment]
Should sonar run on other branches than master? I think ultimately just master should be sufficient. What do you think @victorhrsilva @kwodzynski @digitalfishpond ?

**Comment by kwodzynski** [comment]
IMHO possibility of analysis code can be useful on each of branches, but for sure it will increase build's time.
for example: previous build 1m 12s, build with sonarqube: 3m 43s

**Comment by victorhrsilva** [comment]
@grubskim I agree that for now just the master is enough, but in a close future, we will need to at least have one branch pre-master to prevent add buggy code to the system.

@kwodzynski For me up to 15 minutes is acceptable.

**Comment by kwodzynski** [comment]
Sonarqube is set and working correctly. The results of code analysis we can find here: https://sonarqube.com/dashboard/index/org.fujitsu.nephology:nephology for master and here: https://sonarqube.com/dashboard/index/org.fujitsu.nephology:nephology:NAME_OF_YOUR_BRANCH for other branches. 
If you want analysis code of your branch, you have to add the name of branch in .travis.yml:
    branches:
      - master
      - NAME_OF_YOUR_BRANCH
