### ISSUE TITLE
Set up Heroku

### ISSUE THREAD

**Issue by digitalfishpond** [NephologyFJ/nephology#2]
[DoD]
Deployment workflow working for every commit in GitHub

**Comment by digitalfishpond** [comment]
Dawid mentioned something about Heroku supporting Codeship or Semaphore. Are these Technologies you guys know anything about?

**Comment by digitalfishpond** [comment]
We will have to update Definitions of Done ([DoD]) in many of these issues where currently there is only 'To Be Determined' (TBD) @grubskim  @victorhrsilva

**Comment by victorhrsilva** [comment]
Heroku is setup with a very lean architecture for now:
- Only master branch
- Code is pushed to GitHub
- Build and Tested in Travis CI
- If it pass, the Heroku deploy the code straight in production.

P.S.: This architecture will be improved in a short time frame to prevent code be direct to production.
