### ISSUE TITLE
Set up Travis

### ISSUE THREAD

**Issue by digitalfishpond** [NephologyFJ/nephology#5]
[DoD]
Comprehensive tests are set up in Travis (TBD)
Pull requests cannot be merged until Travis tests pass.

**Comment by grubskim** [comment]
Connected our github with travis at:
https://travis-ci.org/NephologyFJ/nephology

The travis build triggers automatically on commit or pull request. Github commits now display if the travis succeded or not.

This required:
1) Adding the .travis.yml file (this keeps the travis configuration if we need to change the deafult process)
2) Everything from this page: https://github.com/mbonaci/mbo-storm/wiki/Integrate-Travis-CI-with-your-GitHub-repo
