### ISSUE TITLE
Set up Performance tests

### ISSUE THREAD

**Issue by digitalfishpond** [NephologyFJ/nephology#9]
[DoD]
It is easy to notice degradation in performance.

**Comment by digitalfishpond** [comment]
Heroku supports BlazeMeter, which may be an option here - we can investigate whether it is possible to link the results to GitHub.

**Comment by victorhrsilva** [comment]
I run a Blazemeter Test for 20 minutes, where 20 users access the index page and it went fine.

However looks like that is very complicated to integrate it with Travis CI, there is even lack of documentation for Performance Tests Tool that provide such kind of integration. 

Is it really needed for now? Can we run it manually?

**Comment by victorhrsilva** [comment]
I sent invitation to you all to register yourselves and be able to access the reports and run the tests, the default link is: https://a.blazemeter.com/app/sign-in.

An open issue for the future if needed will be integrate the performance tests to Travis CI.

**Comment by digitalfishpond** [comment]
We'll create a new issue for that. Closing this one as DoD is met.
